---
# This pipelines definition uses Stages. Make sure the Multi-stage pipelines
# feature (currently in Preview) is turned on:
# https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features
env:
  AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
  AZURE_SECRET: $(AZURE_SECRET)
  AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
  AZURE_TENANT: $(AZURE_TENANT)

trigger:
  - master

stages:
  - stage: Build
    jobs:
      - job: Preview
        pool:
          vmImage: 'ubuntu-16.04'
        container: microsoft/ansible:latest
        steps:
          - bash: set
            displayName: "Check Azure Pipeline Agent Environment Variables"
          - bash: ansible --version; ansible-playbook --version
            displayName: "Check Version of ansible, ansible-playbook"
          - bash: ansible-playbook --syntax-check --connection=local test.yml
            displayName: "Check Ansible Playbook Syntax"
      - job: Check
        pool:
          vmImage: 'ubuntu-16.04'
        container: microsoft/ansible:latest
        steps:
          - bash: ansible-playbook --check --connection=local test.yml
            displayName: "Ansible Playbook Check (Dry Run)"
  - stage: Deploy
    jobs:
      - job: Deploy_Infrastructure
        pool:
          vmImage: 'ubuntu-16.04'
        container: microsoft/ansible:latest
        steps:
          - bash: ansible-playbook --connection=local test.yml
            displayName: "Ansible Playbook Run"
...
