---
trigger:
  - master

jobs:
  - job: Preview
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      azureSubscription: 'Azure RedPoint'
    steps:
      - bash: set
        displayName: "Check Azure Pipeline Agent Environment Variables"
      - bash: ansible-playbook --version
        displayName: "Check Version of ansible-playbook"
      - bash: ansible-playbook --syntax-check --connection=local test.yml
        displayName: "Check Ansible Playbook Syntax"
...
