# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
  inputs:
    - azureSubscription: 'Azure RedPoint'
  - script: set
    displayName: "Check Azure Pipeline Agent Environment Variables"
  - bash: echo "System Access Token: $SYSTEM_ACCESSTOKEN"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - bash: echo "azureSubscription: $(azureSubscription)"
