---
# This pipelines definition uses Stages. Make sure the Multi-stage pipelines
# feature (currently in Preview) is turned on:
# https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines.yml

stages:
  - stage: Build
    jobs:
      - job: Check
        pool:
          vmImage: 'ubuntu-16.04'
        container: microsoft/ansible:latest
        steps:
          - bash: set
            displayName: "Check Azure Pipeline Agent Environment Variables"
          - bash: ansible --version; ansible-playbook --version
            displayName: "Check Version of ansible, ansible-playbook"
          - bash: ansible-doc --list
            displayName: "Check Installed Ansible Modules with ansible-doc"
          - bash: ansible-playbook --syntax-check --connection=local site.yml --extra-vars "client_id=$(CLIENT_ID)"
            displayName: "Check Ansible Playbook Syntax"
      - job: Preview
        pool:
          vmImage: 'ubuntu-16.04'
        container: microsoft/ansible:latest
        steps:
          - bash: |
              echo "CLIENT_ID: $(CLIENT_ID)"
              echo "AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)"
              echo "AZURE_SECRET: $(AZURE_SECRET)"
              echo "AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)"
              echo "AZURE_TENANT: $(AZURE_TENANT)"
              ansible-playbook --check --connection=local site.yml --extra-vars "client_id=$(CLIENT_ID)"
            displayName: "Ansible Playbook Check (Dry Run)"
  - stage: Deploy
    jobs:
      - job: Deploy_Infrastructure
        pool:
          vmImage: 'ubuntu-16.04'
        container: microsoft/ansible:latest
        steps:
          - bash: set
            displayName: "DEBUG - Check Azure Pipeline Agent Environment Variables"
          - bash: ansible-playbook --connection=local site.yml --extra-vars "client_id=$(CLIENT_ID)"
            displayName: "Ansible Playbook Run"
...
