# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Preview
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    azureSubscription: 'Azure RedPoint'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  steps:
    - script: set
      displayName: "Check Azure Pipeline Agent Environment Variables"
    - bash: echo "System Access Token: $SYSTEM_ACCESSTOKEN"
    - bash: echo "azureSubscription: $(azureSubscription)"
