---
- hosts: localhost
  vars:
    do_build: true
    do_destroy: false
    do_rebuild: false
    build_env: 'UNDEFINED'

  tasks:

    - debug:
        var: build_env
    - debug:
        var: do_build
    - debug:
        var: do_destroy
    - debug:
        var: do_rebuild

    - name: Resource Group Absent
      azure_rm_resourcegroup:
        name: "cf-lab-{{ client_id }}-{{ build_env }}"
        location: northcentralus
        # force_delete_nonempty: true # Ansible 2.8+
        force: true # Ansible 2.7
        state: absent
      register: rg_destroy
      when: do_destroy == true or do_rebuild == true

    - debug:
        var: rg_destroy

    - name: Resource Group Present
      azure_rm_resourcegroup:
        name: "cf-lab-{{ client_id }}-{{ build_env }}"
        location: northcentralus
        state: present
      register: rg
      when: do_build == true or do_rebuild == true

    - debug:
        var: rg
...
