---
- hosts: localhost
  connection: local

  tasks:
  - name: Resource Group
    azure_rm_resourcegroup:
      name: cf-lab
      location: northcentralus
      tags:
        automation: 'ansible-azdo'
        environment: lab
        owner: craigf

...
