---
- hosts: localhost
  vars:
    do_destroy: False
    do_build: True

  tasks:

    - name: Resource Group Absent
      azure_rm_resourcegroup:
        name: "cf-lab-{{ client_id }}"
        location: northcentralus
        state: absent
      register: rg
      when: do_destroy

    - name: Resource Group Present
      azure_rm_resourcegroup:
        name: "cf-lab-{{ client_id }}"
        location: northcentralus
        state: present
      register: rg
      when: do_build

    - debug:
        var: rg
...
