---
- hosts: localhost
  vars:
    do_build: True
    do_destroy: False
    do_rebuild: False

  tasks:

    - debug:
        var: do_build

    - debug:
        var: do_destroy

    - debug:
        var: do_rebuild

    - name: Resource Group Absent
      azure_rm_resourcegroup:
        name: "cf-lab-{{ client_id }}"
        location: northcentralus
        force_delete_nonempty: true
        state: absent
      register: rg_destroy
      when: do_destroy or do_rebuild

    - debug:
        var: rg_destroy

    - name: Resource Group Present
      azure_rm_resourcegroup:
        name: "cf-lab-{{ client_id }}"
        location: northcentralus
        state: present
      register: rg
      when: do_build or do_rebuild

    - debug:
        var: rg
...
