---
- hosts: localhost
  tasks:
    - name: Resource Group
      azure_rm_resourcegroup:
        name: "cf-lab-{{ client_id }}"
        location: northcentralus
      register: rg
    - debug:
        var: rg
...
