---
- hosts: localhost
  vars:
    build_env: 'UNDEFINED'
    build_action: 'build'

  tasks:

    - debug:
        var: build_env
    - debug:
        var: build_action

    - name: Resource Group Absent
      azure_rm_resourcegroup:
        name: "cf-lab-{{ client_id }}-{{ build_env }}"
        location: northcentralus
        # force_delete_nonempty: true # Ansible 2.8+
        force: true # Ansible 2.7
        state: absent
      register: rg_destroy
      when: ("destroy" in build_action) or ("rebuild" in build_action)

    - debug:
        var: rg_destroy

    - name: Resource Group Present
      azure_rm_resourcegroup:
        name: "cf-lab-{{ client_id }}-{{ build_env }}"
        location: northcentralus
        state: present
      register: rg_build
      when: "build" in build_action

    - debug:
        var: rg_build
...
