---
# azure_network/tasks/main.yml
- name: Public IP of Ansible Controller (ipify)
  ipify_facts:
    api_url: https://api.ipify.org
    timeout: 20

- name: Virtual Network
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ virtual_network }}"
    address_prefixes: "10.99.0.0/16"
    state: present

- name: Network Security Group
  vars:
    ansible_public_ip: "{{ ipify_public_ip }}"
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ subnet }}-nsg"
    state: present
    purge_rules: False

- name: Virtual Network Subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ subnet }}"
    address_prefix: "10.99.0.0/24"
    virtual_network: "{{ virtual_network }}"
    security_group: "{{ subnet }}-nsg"
    state: present
...
