---
# azure_core/tasks/main.yml
- debug:
    var: build_env
- debug:
    var: build_action

- set_fact:
    resource_group: "cf-lab-{{ client_id }}-{{ build_env }}"
    region: northcentralus
    virtual_network: "{{ resource_group }}-vnet"
    subnet: "{{ resource_group }}-subnet1"

- name: Resource Group Absent
  azure_rm_resourcegroup:
    name: "cf-lab-{{ client_id }}-{{ build_env }}"
    location: "{{ region }}"
    # force_delete_nonempty: true # Ansible 2.8+
    force: true # Ansible 2.7
    state: absent
  register: rg_destroy
  when: "'destroy' in build_action"

- debug:
    var: rg_destroy

- name: Resource Group Present
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ region }}"
    state: present
  register: rg_build
  when: "'build' in build_action"

- debug:
    var: rg_build
...
